language: scala
dist: xenial
sudo: false

scala:
  - 2.11.12
  - 2.12.8
  # - 2.13.0-M4

jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    # - jdk: openjdk11
    #   scala: 2.13.0-M4
    - jdk: openjdk-ea

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.coursier

install:
  - pip install --user codecov

script:
  - |
    if [[ "$TRAVIS_JDK_VERSION" = "openjdk8" && "$TRAVIS_SCALA_VERSION" = 2.12.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION clean coverage compile test:compile test coverageReport coverageOff && codecov
    elif [[ "$TRAVIS_SCALA_VERSION" = 2.13.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION! clean \
        core/compile core/test:compile core/test \
        cats-effect/compile cats-effect/test:compile cats-effect/test
    else
      sbt ++$TRAVIS_SCALA_VERSION clean compile test:compile test
    fi
  - |
    if [[ "$TRAVIS_JDK_VERSION" = "openjdk8" && $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
      export PGP_SECRET_RING="${HOME}/.gnupg/secring.gpg"
      mkdir -p $(dirname "${PGP_SECRET_RING}")
      echo $GPG_KEY | base64 --decode > "${PGP_SECRET_RING}"
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
          sbt ++$TRAVIS_SCALA_VERSION publishSigned
        else
          if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
            sbt ++$TRAVIS_SCALA_VERSION publishLocalSigned
          else
            sbt ++$TRAVIS_SCALA_VERSION publishLocal
          fi
        fi
      fi
    fi


after_script:
  # See http://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
